#!/bin/sh
#
# Apply fixed TTL / hop-limit on the modem network interface.
# Usage:
#   ttl.sh apply   - regenerate the nftables include from uci and reload fw4
#   ttl.sh get     - print current values + detected device as JSON
#
# TTL values live in uci: 5gmodem.@5gmodem[0].{ttl4in,ttl4out,ttl6in,ttl6out}
# Empty value = leave that direction/family untouched.
#

CFG=5gmodem
NFT=/etc/nftables.d/10-5gmodem-ttl.nft

modem_iface() {
	# configured interface first, then the first control-proto interface
	I=$(uci -q get $CFG.@5gmodem[0].network)
	if [ -z "$I" ]; then
		for P in atc modemmanager qmi mbim ncm wwan; do
			I=$(uci show network 2>/dev/null | sed -n "s/^network\.\([^.]*\)\.proto='$P'\$/\1/p" | head -1)
			[ -n "$I" ] && break
		done
	fi
	echo "$I"
}

l3dev() {
	ifstatus "$1" 2>/dev/null | sed -n 's/.*"l3_device": *"\([^"]*\)".*/\1/p' | head -1
}

case "$1" in
set)
	# ttl.sh set <ttl4in> <ttl4out> <ttl6in> <ttl6out>  (empty = off)
	for f in ttl4in:2 ttl4out:3 ttl6in:4 ttl6out:5; do
		k=${f%%:*}; n=${f##*:}; eval v="\$$n"
		case "$v" in ''|*[!0-9]*) uci -q delete $CFG.@5gmodem[0].$k;; *) uci set $CFG.@5gmodem[0].$k="$v";; esac
	done
	uci commit $CFG
	"$0" apply
	;;
get)
	IFACE=$(modem_iface)
	DEV=$(l3dev "$IFACE")
	DEF4=$(sysctl -n net.ipv4.ip_default_ttl 2>/dev/null); [ -n "$DEF4" ] || DEF4=64
	DEF6=$(sysctl -n net.ipv6.conf.all.hop_limit 2>/dev/null); [ -n "$DEF6" ] || DEF6=64
	printf '{"iface":"%s","device":"%s","def4":"%s","def6":"%s","ttl4in":"%s","ttl4out":"%s","ttl6in":"%s","ttl6out":"%s"}\n' \
		"$IFACE" "$DEV" "$DEF4" "$DEF6" \
		"$(uci -q get $CFG.@5gmodem[0].ttl4in)" \
		"$(uci -q get $CFG.@5gmodem[0].ttl4out)" \
		"$(uci -q get $CFG.@5gmodem[0].ttl6in)" \
		"$(uci -q get $CFG.@5gmodem[0].ttl6out)"
	;;

apply)
	IFACE=$(modem_iface)
	DEV=$(l3dev "$IFACE")
	T4I=$(uci -q get $CFG.@5gmodem[0].ttl4in)
	T4O=$(uci -q get $CFG.@5gmodem[0].ttl4out)
	T6I=$(uci -q get $CFG.@5gmodem[0].ttl6in)
	T6O=$(uci -q get $CFG.@5gmodem[0].ttl6out)

	mkdir -p /etc/nftables.d
	{
		echo "# generated by luci-app-5gmodem - do not edit"
		if [ -n "$DEV" ]; then
			[ -n "$T4I" ] && echo "chain mangle_prerouting { iifname \"$DEV\" ip ttl set $T4I; }"
			[ -n "$T4O" ] && echo "chain mangle_postrouting { oifname \"$DEV\" ip ttl set $T4O; }"
			[ -n "$T6I" ] && echo "chain mangle_prerouting { iifname \"$DEV\" ip6 hoplimit set $T6I; }"
			[ -n "$T6O" ] && echo "chain mangle_postrouting { oifname \"$DEV\" ip6 hoplimit set $T6O; }"
		fi
	} > "$NFT"

	# nothing to enforce -> remove the include so no empty rules linger
	[ -s "$NFT" ] && ! grep -q "chain " "$NFT" && rm -f "$NFT"

	fw4 reload >/dev/null 2>&1
	echo "OK"
	;;

*)
	echo "usage: $0 apply|get" >&2
	exit 1
	;;
esac
